# https://nurbs-python.readthedocs.io/en/latest/

# Use RTD latest python image
build:
  image: latest

# Build HTML and PDF docs
formats:
  - htmlzip
  - pdf

# Python options
python:
  version: 3
  use_system_site_packages: true  # needed for numpy, matplotlib, etc.
