# https://travis-ci.org/orbingol/NURBS-Python

dist: xenial
sudo: false

language: python

# branches to build
branches:
  only:
    - master  # latest version
    - devmaster  # latest development version
    - 4.x  # v4.x series
    - 3.x  # v3.x series
    - 2.x  # v2.x series
    - travisci-testing  # Travis-CI testing

# build matrix
matrix:
  include:
    - python: 2.7
      env: TOXENV=full-py27,core-py27,codecov

    - python: 3.4
      env: TOXENV=full-py34,core-py34

    - python: 3.5
      env: TOXENV=full-py35,core-py35

    - python: 3.6
      env: TOXENV=full-py36,core-py36

    - python: 3.7
      env: TOXENV=full-py37,core-py37,codecov

    - python: pypy3.5
      env: TOXENV=full-pypy3

# install packages
install:
  - pip install tox

# run tox
script:
  - tox
