# https://circleci.com/gh/orbingol/NURBS-Python

# Define anchor "defbase"
defbase: &defbase
  docker:
    - image: circleci/buildpack-deps:bionic
  working_directory: ~/nurbslib  # creates /home/circleci/nurbslib

# Define anchor "defsteps"
defsteps: &defsteps
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: echo 'export IMAGE=geomdl-$TAG' >> $BASH_ENV
    - run: docker build -t $IMAGE docker/$TAG
    - run: |
        echo $DOCKER_HUB_PASSWD | docker login -u $DOCKER_HUB_USERID --password-stdin
        docker tag $IMAGE $DOCKER_HUB_ORG/$DOCKER_HUB_REPO:$TAG
        docker push $DOCKER_HUB_ORG/$DOCKER_HUB_REPO

# Define build jobs
version: 2
jobs:
  docker_py27:
    <<: *defbase
    environment:
      TAG: py27  # Docker tag as an environmental variable
    <<: *defsteps

  docker_py35:
    <<: *defbase
    environment:
      TAG: py35  # Docker tag as an environmental variable
    <<: *defsteps

  docker_py36:
    <<: *defbase
    environment:
      TAG: py36  # Docker tag as an environmental variable
    <<: *defsteps

  docker_py37:
    <<: *defbase
    environment:
      TAG: py37  # Docker tag as an environmental variable
    <<: *defsteps

# Define workflows
workflows:
  version: 2
  build_docker:
    jobs:
      - docker_py27:
          filters:
            branches:
              only:
                - master
                - circle-ci-testing
      - docker_py35:
          filters:
            branches:
              only:
                - master
                - circle-ci-testing
      - docker_py36:
          filters:
            branches:
              only:
                - master
                - circle-ci-testing
      - docker_py37:
          filters:
            branches:
              only:
                - master
                - circle-ci-testing
