# conda-build recipe for NURBS-Python (geomdl) package
{% set setup_data = load_setup_py_data() %}
{% set build_number = 0 %}

package:
  name: geomdl
  version: {{ setup_data['version'] }}

source:
  path: ../../

build:
  noarch: python
  number: {{ build_number }}
  script:
    - python setup.py sdist
    - pip install dist/geomdl-{{ setup_data['version'] }}.tar.gz --no-deps

requirements:
  host:
    - python
    - setuptools
    - six
    #- functools_lru_cache
    - typing
  run:
    - python
    - six
    #- functools_lru_cache
    - typing
    - numpy
    - matplotlib

test:
  imports:
    - geomdl
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - python -c "import geomdl; print(geomdl.__version__)"
    - pytest

about:
  home: https://onurraufbingol.com/NURBS-Python/
  license: MIT
  license_file: ../../LICENSE
  summary: Object-oriented B-Spline and NURBS evaluation library
  description: "Self-contained, object-oriented, pure Python B-Spline and NURBS evaluation library with knot vector and surface grid generators."
  doc_url: "http://nurbs-python.readthedocs.io/"
  dev_url: "https://github.com/orbingol/NURBS-Python"

extra:
  recipe-maintainers:
    - orbingol
